### ISSUE TITLE
Lineages.yml missing some children 

### ISSUE THREAD

**Issue by joshuailevy** [cov-lineages/lineages-website#19]
Hi!
I've noted that on occasion some of the children of a lineage won't be included, particularly if there is a jump in the nomenclature. For example, BF.1 is a descendant of BA.5, but doesn't appear in the list of BA.5's children. The parent of BF.1 is listed as B.1.1.529.5.2.1, so I could imagine it's possible that this is due to there being multiple names for BA.5.2.1? Or perhaps I can reconstruct this relationship between BF.1 and BA.5 some other way using the lineages.yml file? 

Thanks so much for the incredible resource and help! 
Josh

**Comment by jubileepower** [comment]
Hi Pango team, I'm writing to echo the point above. I recently had to deal with the same issues with my scripts. There are two things at play. 

1. The following parents within the yaml file did not use the alias, while in children and name the BA.blah aliases were used. This causes a disconnect when tracing up the lineage, but can be fixed by renaming B.1.1.529. to BA. ."B.1.1.529.1.1.1,B.1.1.529.1.17.2,B.1.1.529.2.10.1,B.1.1.529.2.12.1,B.1.1.529.2.38.3,B.1.1.529.2.75.1,B.1.1.529.2.75.3,B.1.1.529.5.1.10,B.1.1.529.5.2.1,B.1.1.529.5.3.1"

2.  Another issue is missing children. Eg. for name=BA.5.2.1, there is no children except itself, while name=BF.1, it notes B.1.1.529.5.2.1 as parent (with renaming in step1, it can be BA.5.2.1). However, the relation is non-mutual, and can cause another disconnect for some usage.

I've written the script for my information extraction to work around the two issues above, but if it's possible to modify the yml file from the source, it would be great for everyone.

Thanks!

**Comment by joshuailevy** [comment]
Hey Julie, 
For the moment, you might be interested in the patched version we're currently hosting on the outbreak.info repo (updated along with new pango designations). Should hopefully solve most of your issues , until a proper update to the version hosted here is available. https://github.com/outbreak-info/outbreak.info/blob/master/curated_reports_prep/lineages.yml
Josh

**Comment by TheZetner** [comment]
There seems to be a good amount of trouble and interest surrounding this hierarchy of PANGO lineages. Maybe not the right place to make the suggestion but this information has to exist in the PLEARN model, right? Perhaps there should be a command line option like `pangolin --hierarchy` to output a simple YAML or Newick like we're seeing in multiple places online.

**Comment by rmcolq** [comment]
Closing as stale
